[package]
name = "xtraceroute"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
traceroute = "0.1.1"
clap = "2.32.0"
trust-dns-resolver = "0.9.1"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
hostname = "0.1.5"
